### ISSUE TITLE
Please make sure [docker] can be executed on this agent.

### ISSUE THREAD

**Issue by shaunluttin** [gocd/docker-gocd-agent-ubuntu-18.04#2]
How do we ensure docker can be executed on this agent?

This is the error message: 
```
[go] Task: docker build --no-cache --tag farm_app_image:latest --file Dockerfile .took: 0.20s
    Error happened while attempting to execute 'docker build --no-cache --tag farm_app_image:latest --file Dockerfile .'. 
    Please make sure [docker] can be executed on this agent.
```

This is the configuration:

![image](https://user-images.githubusercontent.com/2066637/68987459-28183d00-07df-11ea-8790-e2506e0cb50d.png)

**Comment by shaunluttin** [comment]
This is our current approach: 

```
# start the agent's container
docker start  hungry_lalande

# attach to the docker agent as root
sudo docker exec --user root -i -t hungry_lalande /bin/bash

# install docker
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh

# Add the GoCD user to the docker group
usermod -aG docker go
```

**Comment by ketan** [comment]
That sounds about right, assuming you're trying to do docker-out-of-docker. You may be able to make an improvement if you put these commands in a `Dockerfile` and bake an image out of it.

**Comment by ketan** [comment]
Also: closing since this is more of a question that's more suited for the gocd forums, than an issue with gocd.
